Added documentation for known methods.
liquality/chainabstractionlayer pull request #11
Opened 2018-07-19 18:13 UTC by i3wgnit

I have a few more prepared, however, more discussion is needed to confirm the
arguments.

2018-07-19 18:16 UTC, i3wgnit commented
We should gitignore `docs/`
The deltas are stupid (+6k, -4k) for some documentation.

2018-07-24 13:19 UTC, harshjv requested changes
Can you fetch the latest changes and rebase? docs building on git commit is already disabled.

2018-07-24 13:19 UTC, harshjv commented on src/index.js
> +    this._checkMethod('getRawTransactionByHash')
Did you forget to call `this.provider. getRawTransactionByHash`?

2018-07-24 13:21 UTC, i3wgnit commented on src/index.js
> +    this._checkMethod('getRawTransactionByHash')
i didn't add any of the code in. Just the documentation. I could add it today if you want.

2018-07-24 13:22 UTC, harshjv commented on src/index.js
> +    this._checkMethod('getRawTransactionByHash')
okay then. make sure when you push commits, you rebase first :)

2018-07-26 14:00 UTC, closed without merging