Implement some Bitcoin RPC Provider Methods
liquality/chainabstractionlayer pull request #13
Opened 2018-07-25 20:19 UTC by i3wgnit

Implemented the following:
- getBlockByHash
- getBlockByNumber
- getTransactionByHash
- getRawTransactionByHash
- _decodeRawTransaction

2018-07-25 21:09 UTC, monokh commented on src/index.js
> +   * @param {!string} blockHash - A hexadecimal string that represents the *hash* of the desired block. If txHash is not a string, it will get converted through the `toString(16)` method.
I think the value of block hash should be consistent. So only accepts string and the user of the library can provide it like that

2018-07-25 21:36 UTC, monokh commented on src/index.js
> +   * @param {!string} txHash - A hexadecimal string that represents the *hash* of the desired transaction. If `hash` is not a string, it will be converted through the `toString(16)` method.
Similar to previous comment about consistent type for this parameter

2018-07-25 22:10 UTC, monokh reviewed
Looks good. 

Good on removing the dist folder, it's very confusing when looking at PRs. Anyone that needs the dist can generate on demand with the code. 
Probably same for doc html, should figure a way to remove it since it's already inside the code.

2018-07-25 22:11 UTC, monokh commented
@harshjv the build somehow still failing on the node-hid installation 😿

2018-07-26 04:23 UTC, harshjv commented
@i3wgnit thanks for removing `dist` from git! I am also going to gitignore `docs`.

@mattBlackDesign any update on adding `libusb` to the docker image?

2018-07-26 04:34 UTC, harshjv requested changes
Do add `docs/` to .gitignore for now. I will setup docs building through CI later.

2018-07-26 04:34 UTC, harshjv commented on src/index.js
> +   * @param {!string} txHash - A hexadecimal string that represents the *hash* of the desired transaction. If txHash is not a string, it will get converted through the `toString(16)` method.
We are already expecting a string here. No need of `If txHash is not a string, it will get converted through the `toString(16)` method.`

2018-07-26 04:34 UTC, harshjv commented on src/providers/bitcoin/BitcoinRPCProvider.js
> +    transactionHash = typeof transactionHash === 'string' ? transactionHash : transactionHash.toString(16)
same here. `transactionHash` is a string. Add a check using `isString` instead.

2018-07-26 04:34 UTC, harshjv commented on src/schema/Block.json
> +      "type": "string",
Why `string`? Returning number in hex?

2018-07-26 04:34 UTC, harshjv commented on src/providers/bitcoin/BitcoinRPCProvider.js
> +    Object.assign(tx, { confirmations })
Better way of using `Object.assign` is using traditional assignment statement and an empty object:

    const newObject = Object.assign({}, tx, { confirmations })

This also keeps original object `tx` intact.

2018-07-26 06:42 UTC, i3wgnit commented on src/schema/Block.json
> +      "type": "string",
`difficulty` is a number in scientific notation given as a string.

2018-07-26 07:05 UTC, harshjv commented on src/schema/Block.json
> +      "type": "string",
Returning `string(number)` i.e. `"5178671069072.25"` makes more sense to me instead of scientific notation. Later, library like `BigNumber` can be used to manipulate the property.

2018-07-26 14:44 UTC, harshjv requested changes
Looking forward to the updates!

2018-07-26 14:44 UTC, harshjv commented on src/schema/Block.json
>        "minimum": 0
String doesn't have `minimum` property in JSON Schema. You can use `minLength/maxLength` instead.

2018-07-26 14:44 UTC, harshjv commented on src/index.js
> +   * @return {Promise<Client.schemas.Block, null>} Returns a Block with the same hash as the given input. Returns null if no block was found. If `includeTx` is true, the transaction property is an ar
In `Promise<Client.schemas.Block, null>`, second parameter is for the error when `Promise` is rejected. So in this case, it will be `Error`

2018-07-26 14:44 UTC, harshjv commented on src/index.js
> +    if (!(/^(0x)?[A-Fa-f0-9]+$/.test(blockHash))) {
Didn't we decide to enforce no `0x` prefix?

2018-07-26 14:44 UTC, harshjv commented on src/index.js
> +   * @return {Promise<Client.schemas.Block, null>} Returns a Block with the same number as the given input. Returns null if no block was found. If `includeTx` is true, the transaction property is an
Same here regarding the second parameter.

2018-07-26 14:44 UTC, harshjv commented on src/index.js
> +   * @return {Promise<number>}
`Error` as second parameter.

2018-07-26 14:44 UTC, harshjv commented on src/index.js
> +   * @return {Promise<Client.schemas.Transaction, null>} Returns a Transaction with the same hash as the given input. Returns null if no transaction was found.
Same here.

2018-07-26 14:44 UTC, harshjv commented on src/index.js
> -    if (!(/^[A-Fa-f0-9]$/.test(txHash))) {
Can we check for hex here?

2018-07-26 14:44 UTC, harshjv commented on src/index.js
> +  async getRawTransactionByHash (txHash) {
Same here.

2018-07-26 14:44 UTC, harshjv commented on src/index.js
> +    const transaction = await this.provider.getRawTransactionByHash(txHash.replace('0x', ''))
No need to replace `0x` if early checks throw an error on such strings.

2018-07-26 14:48 UTC, i3wgnit commented on src/index.js
> -    if (!(/^[A-Fa-f0-9]$/.test(txHash))) {
i have it a bit more down right?

2018-07-26 14:58 UTC, harshjv approved these changes
LGTM

2018-07-26 14:58 UTC, merged