Implement generate swap for Bitcoin and Ethereum
liquality/chainabstractionlayer pull request #15
Opened 2018-07-26 15:57 UTC by i3wgnit

2018-07-26 15:59 UTC, monokh commented on src/index.js
> +    const swap = this.provider.generateSwap(recipientAddress, refundAddress, secretHash, expiration)
can do return right here

2018-07-26 16:01 UTC, monokh commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +    return `76a97263a914${secretHash}8814${recipientAddress}67${exLen.toString(16).padStart(2, '0')}${expiration}b16d14${refundAddress}6888ac`
can this become multi line so it's a little easier to read

2018-07-26 16:04 UTC, monokh submitted a review, later dismissed
nice one, could you also bring the tests in here?

2018-07-26 16:04 UTC, monokh commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +    expiration = expiration.toString(16)
it's generally not good to reassign variables
how about something like `const expirationHex = expiration.toString(16)`?

2018-07-27 14:31 UTC, harshjv commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +    //         # Prep inputed PK for PKH check
Should we move logic to generate swap in a separate swap-specific library?

2018-07-27 14:33 UTC, i3wgnit commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +    //         # Prep inputed PK for PKH check
But its a pain to add new providers right now.
I can make a BitcoinSwapProvider.js that extends Ledger if you prefer

2018-07-27 14:38 UTC, harshjv commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +    //         # Prep inputed PK for PKH check
I meant moving swap-specific logic and code to a new `liquality-swap` library maybe?

2018-07-27 17:06 UTC, matthewjablack commented on src/providers/ethereum/EthereumMetaMaskProvider.js
> +    const secretHashEncoded = secretHash.replace('0x', '') // Remove 0x if exists
Some documentation comments would be nice for constants in generateSwap

2018-07-27 21:47 UTC, monokh commented on src/index.js
> +    if (!(/^[A-Fa-f0-9]+$/.test(recipientAddress))) {
probably better if we make this an `isHex` utility? then easier to read the validations because there are a lot 😄

2018-07-27 21:53 UTC, monokh commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +    //         # Prep inputed PK for PKH check
I think it's fine to have the swap generation here, this way it's an interface of the CAL. If others want to develop swap generations that are different or for other chains, they can implement it as part of a provider. 
As a slightly neater solution, another provider could implement the generateSwap e.g. `BitcoinSwapProvider`? 
For the sake of getting stuff done, i think we should take the path of least resistance in getting the MVP working

2018-07-27 21:54 UTC, monokh commented on src/providers/ethereum/EthereumMetaMaskProvider.js
> +    const secretHashEncoded = secretHash.replace('0x', '') // Remove 0x if exists
This was my code actually 😄 
Perhaps add a little bit about the op codes or what the destinations mean? Generally, I would say it's pretty well documented just with how I split up every calculations name

2018-07-30 09:45 UTC, harshjv commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +    return `76a97263a914${secretHash}8814${recipientAddress}67${expirationHex.length.toString(16).padStart(2, '0')}${expirationHex.join('')}b16d14${refundAddress}6888ac`
I am not confident about adding such a code snippet in our library. Modification to this code snippet is not going to be a fun task. It is not expressive and is prone to error.

2018-07-30 09:45 UTC, harshjv commented on src/providers/ethereum/EthereumMetaMaskProvider.js
> +    return `60${dataSizeEncoded}80600b6000396000f36020806000803760218160008060026048f17f\
Same here. See my previous comment :)

2018-07-30 09:45 UTC, harshjv commented on src/index.js
> +    if (!(/^[A-Fa-f0-9]+$/.test(recipientAddress))) {
Yup! How about we use this library: https://www.npmjs.com/package/type-check

2018-07-30 10:13 UTC, monokh commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +    return `76a97263a914${secretHash}8814${recipientAddress}67${expirationHex.length.toString(16).padStart(2, '0')}${expirationHex.join('')}b16d14${refundAddress}6888ac`
I see this as a temporary thing but what would be the alternative? I think we would either need to remove generating swaps from this library entirely or integrate bitcoin script / eth contract compilers into the library. I thought there were concerns around introducing huge libraries

2018-07-30 10:24 UTC, harshjv commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +    return `76a97263a914${secretHash}8814${recipientAddress}67${expirationHex.length.toString(16).padStart(2, '0')}${expirationHex.join('')}b16d14${refundAddress}6888ac`
Can we do something like this?

```
const OP_MAP = {
  OP_DUP: '76',
  OP_HASH160: 'a9',
  OP_2SWAP: '72',
  OP_IF: '63',
  OP_EQUALVERIFY: '88',
  OP_ELSE: '67',
  OP_CHECKLOCKTIMEVERIFY: 'b1',
  OP_2DROP: '6d',
  OP_ENDIF: '68',
  OP_CHECKSIG: 'ac'
}

function compile (str) {
  const script = []
  const arr = str.split(' ')

  arr.forEach(v => {
    const code = OP_MAP[v]
    if (code) {
      script.push(code)
    } else {
      // check what is v and substitute proper value
    }
  })

  return script.join('')
}
```

2018-07-30 10:56 UTC, monokh commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +    return `76a97263a914${secretHash}8814${recipientAddress}67${expirationHex.length.toString(16).padStart(2, '0')}${expirationHex.join('')}b16d14${refundAddress}6888ac`
We could do that, but are we then writing our own bitcoin script and ETH contract compilers? If that is not the end goal, it's hard to justify writing this if it's just for one specific script. I think if we decide to put compiling in right now, then we should do it properly. 

Once the script is set and tested there is no real room for modification if not adding an entirely new script. for readability opcodes can be closer to the hexes the represent in the form of comments

2018-07-31 16:40 UTC, i3wgnit commented
Should Swap really be a provider? I feel like it should be something else :confused: It doesn't make sense for us to put all the templates we might write as a provider right?

2018-08-01 21:06 UTC, i3wgnit commented
Should I be the one to introduce type check? Or should this be another PR?

2018-08-02 10:27 UTC, monokh commented
@i3wgnit i think it being inside the provider for now is fine. The providers can be really modular and that's a good thing. We only need swaps at this point. Once/if we have others, we can think about it.

2018-08-02 10:27 UTC, monokh requested changes

2018-08-02 10:27 UTC, monokh commented on src/providers/ethereum/EthereumSwapProvider.js
> +    return bytecode.match(/\S+/g)
I'm concerned about the precedent of introducing bytecode serialising. Let's say, next week we introduced a new script which had a new opcode that wasn't just as easy as `OP_BLA = 0x45`. Would we continue to write bytecode serialising in this library? I think if we are doing bytecode serialising in this project then we should be using a well tested library at that point. Therefore i prefer to not start with this problem until we really need to attend to it and my preference is for something very simple like: 
```
const changeP2PKHScript = [
      '76', // OP_DUP
      'a9', // OP_HASH160
      '14', // data size to be pushed
      changePubKeyHash, // <PUB_KEY_HASH>
      '88', // OP_EQUAL_VERIFY
      'ac' // OP_CHECKSIG
    ].join('')
```

2018-08-03 12:41 UTC, monokh approved these changes

2018-08-06 11:10 UTC, monokh commented
Feel free to merge @i3wgnit CI is failing but matt has fixed this

2018-08-06 14:19 UTC, merged