Ethereum erc20
liquality/chainabstractionlayer pull request #165
Opened 2019-04-02 13:44 UTC by jdourlens

:warning: THIS IS A PULL REQUEST TEMPLATE! :warning: This helps you complete a pull request. Please follow the instructions below. Reminder that you are bound to abide by the [Code of Conduct](./CODE_OF_CONDUCT.md)

### Description

Add ERC20 Swap provider.

### Submission Checklist :pencil:

- [ ] Enables Transfer, balance of ERC20 tokens
- [ ] Enables Swaps of ERC20 tokens

2019-04-02 13:51 UTC, jdourlens commented
for runing test on Ganache there is a bug and need to add 
```
      gasPrice: 8000000000,
      gas: 4700000
```

in the EthereumRPCProvider line 38

2019-04-03 10:00 UTC, monokh requested changes
Great work. some suggestions

2019-04-03 10:00 UTC, monokh commented on src/providers/ethereum/EthereumERC20Provider.js
> +  erc20Transfer (to, value) {
Isn't this essentially an implementation of `sendTransaction`? if you have added an ERC20 provider to your client, you want to be able to do `clientErc20.sendTransaction('0x0000', 10000000)` and it will transfer the erc20. Using the standard interface. 
By the way, you can still call `sendTransaction` within the function, it will look through the stack of providers and find the next in line.

2019-04-03 10:00 UTC, monokh commented on src/providers/ethereum/EthereumERC20Provider.js
> +  erc20 () {
Are these 2 functions necessary? Seems like we can just access this._contractAddress in any case.

2019-04-03 10:00 UTC, monokh commented on src/providers/ethereum/EthereumERC20Provider.js
> +  async getBalance (addresses) {
Bit of an odd construct. If it just relays the call to erc20Balance, why not just include the content of that function here?

2019-04-03 10:00 UTC, monokh commented on src/providers/ethereum/EthereumERC20Provider.js
> +  // TODO not used anymore (was only there for tests)
Please remove the functions if not used 😃 can always add back later if needed

2019-04-03 10:00 UTC, monokh commented on src/providers/ethereum/EthereumERC20SwapProvider.js
> +    /* Source of the compiled Bytecode
Nice one, i think this is a good to be more transparent

2019-04-03 10:00 UTC, monokh commented on src/providers/ethereum/EthereumERC20SwapProvider.js
> +    await this.getMethod('sendTransaction')(null, 0, bytecode)
Referring to my previous comment about implementing erc20transfer as `sendTransaction`, i can see why this might not work now...

2019-04-03 10:00 UTC, monokh commented on src/providers/ethereum/EthereumERC20SwapProvider.js
> +    let contractBalanceMatchesValue = false
Why does initiating need to wait for the balance? When waiting for initiation to complete, someone would just use `findInitiateSwapTransaction` i would think. That's how its' generally done with the other assets

2019-04-03 10:00 UTC, monokh commented on src/providers/ethereum/EthereumERC20SwapProvider.js
> +    return transactionMatchesSwapParams && initiationTransactionReceipt.status === '1'
The balance should be checked here i would think. 
Doesn't need to scan for it though

2019-04-03 10:00 UTC, monokh commented on test/integration/swap/singleChain.js
> +  describe('ERC20 - MetaMask', () => {
I know you don't have a ledger atm, but even if you can't test it, could you add the one with ledger too?

2019-04-03 10:00 UTC, monokh commented on test/integration/swap/common.js
> +    client.getMethod('setErc20')(initiationTransactionReceipt.contractAddress)
I would rather use some hacky way of setting the `._contractAddress` of the provider - like iterating through the providers and setting it, rather than have an exposed method on the client for that purpose

2019-04-03 10:00 UTC, monokh commented on test/integration/swap/common.js
> +function connectMetaMask (client) {
Doesn't seem to be using the `client`

2019-04-03 10:41 UTC, harshjv commented on src/providers/ethereum/EthereumERC20Provider.js
> +const sleep = ms => new Promise(resolve => setTimeout(resolve, ms))
We are using this code very frequently in our codebase. Can we move it to a utility file?

2019-04-03 15:29 UTC, monokh requested changes
everything looking good! i just think i spotted an accident with git

2019-04-03 15:29 UTC, monokh commented on src/providers/ethereum/EthereumRPCProvider.js
> -  async sendRawTransaction (hash) {
nooooooo, we need these :( accident maybe?

2019-04-03 15:50 UTC, monokh approved these changes
LGTM 🎉 🎈 🇪🇹 !!!!

2019-04-03 15:56 UTC, merged