Normalize Ethereum
liquality/chainabstractionlayer pull request #17
Opened 2018-07-26 20:50 UTC by matthewjablack

This PR normalizes date received from Ethereum by implementing `Ethereum Utils`.

2018-07-27 14:27 UTC, harshjv requested changes

2018-07-27 14:27 UTC, harshjv commented on src/schema/Block.json
> +      "pattern": "^([0x]{2}?)([A-Fa-f0-9]{64})$"
Hey @mattBlackDesign, you can remove `0x` from prefix.

2018-07-27 14:27 UTC, harshjv commented on src/index.js
> +    // const valid = this.validateBlock(block)
Why is this in comments? Skipping block test?

2018-07-27 14:27 UTC, harshjv commented on src/index.js
> +    // if (!isString(txHash)) {
and this too?

2018-07-27 17:07 UTC, matthewjablack commented
@harshjv this PR allows CAL to work properly with both Bitcoin and Ethereum Multi Chain Block explorer demo. I'll modify this PR to standardize Ethereum to remove 0x at beginning of each attribute

2018-07-30 19:53 UTC, matthewjablack commented
@harshjv  I've updated the PR with normalization of data from ethereum chain

2018-07-30 20:11 UTC, monokh commented on src/index.js
> +      console.log(this.validateTransaction.errors)
probably better to include this in the error you are throwing? Will still get it logged + the metadata of the error is also carried through

2018-07-30 20:13 UTC, monokh commented on src/providers/ethereum/EthereumUtil.js
> +function formatEthHex (match, p1, p2, offset, string) {
this is quite an odd function 😃 can you describe it?

2018-07-30 20:16 UTC, monokh commented on src/providers/ethereum/EthereumUtil.js
> +      if (obj[i].startsWith('0x')) {
Could this test and replace be just `obj[i].replace('0x', '')` ?

2018-07-31 10:40 UTC, harshjv requested changes

2018-07-31 10:40 UTC, harshjv commented on src/index.js
> +      console.log(this.validateBlock.errors)
no debugging related `console.log` in `master` 🙅🏻‍♂️

2018-07-31 10:40 UTC, harshjv commented on src/providers/ethereum/EthereumUtil.js
> +      if (obj[i].startsWith('0x')) {
Can you use functional programming here? `.map` or `.forEach` for consistency?

2018-07-31 13:18 UTC, matthewjablack commented on src/index.js
> +      console.log(this.validateTransaction.errors)
Good idea. Added to errors.

2018-07-31 13:19 UTC, matthewjablack commented on src/providers/ethereum/EthereumUtil.js
> +function formatEthHex (match, p1, p2, offset, string) {
Was using implementation of `.replace` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) but isn't needed anymore 😄

2018-07-31 13:19 UTC, matthewjablack commented on src/providers/ethereum/EthereumUtil.js
> +      if (obj[i].startsWith('0x')) {
Updated to use `.replace` and using `.map`

2018-07-31 13:20 UTC, matthewjablack commented on src/index.js
> +      console.log(this.validateBlock.errors)
Added to error instead 😃

2018-07-31 13:20 UTC, matthewjablack commented
@monokh  @harshjv  updated with your changes

2018-08-02 06:08 UTC, harshjv approved these changes
LGTM. In next sprint, we will need to figure out best way of handling errors and formatting inputs/outputs.

2018-08-02 09:47 UTC, monokh approved these changes
Looks good, no conflicts merging

2018-08-02 09:47 UTC, merged