Add edge case for getBalance where tokenOwner has no balance
liquality/chainabstractionlayer pull request #172
Opened 2019-04-12 05:01 UTC by mattBlackDesign

### Description

This PR adds an edge case for `getBalance` where `tokenOwner` has no balance. Currently this returns `NaN` but it should really return 0

### Submission Checklist :pencil:

- [ ] Add edge case for `getBalance` of `tokenOwner`

2019-04-12 07:11 UTC, harshjv requested changes

2019-04-12 07:11 UTC, harshjv commented on src/providers/ethereum/EthereumERC20Provider.js
> +      .map(balance => parseInt(balance, 16))
There's a catch here. If intermediate address has no balance, this snippet will still return 0.

Instead, if we can check for NaN for each balance and then use `BigNumber` for each (for consistency)

Something like;

    .map(balance => new BigNumber(balance, 16))
    .filter(balance => !balance.isNaN())
    .reduce((acc, balance) => acc.plus(balance), new BigNumber(0))

2019-04-12 07:29 UTC, grandsmarquis approved these changes
Mice catch!

2019-05-15 15:01 UTC, harshjv commented
See #182.

2019-05-15 15:01 UTC, closed without merging