Embracing the new providers model
liquality/chainabstractionlayer pull request #18
Opened 2018-07-27 16:52 UTC by i3wgnit

2018-07-30 10:04 UTC, harshjv requested changes

2018-07-30 10:04 UTC, harshjv commented on src/index.js
> +    if (provider == null) {
It returns `undefined` if it finds nothing. Why are you comparing it loosely (`==`) with `null`?

2018-07-30 10:04 UTC, harshjv commented on src/Provider.js
> +    return this.client.getProviderForMethod(method, this)[method]
This won't work. Need to bind function to the provider first.

2018-07-30 15:02 UTC, i3wgnit commented on src/Provider.js
> +    return this.client.getProviderForMethod(method, this)[method]
This works the first time around, however, adding a provider and using this method in it will remove the this object in the previously added provider.

This should go somewhere at least.

2018-07-30 15:04 UTC, i3wgnit commented on src/index.js
> +    if (provider == null) {
This is how [StandardJs](https://standardjs.com/) says this should be done.
It says to `== null` to check for `null || undefined`.

2018-07-30 15:07 UTC, i3wgnit commented on src/index.js
> +    if (provider == null) {
I quote
> Always use === instead of == – but obj == null is allowed to check null || undefined.

2018-07-30 15:13 UTC, harshjv commented on src/Provider.js
> +    return this.client.getProviderForMethod(method, this)[method]
Change it with this then.

```
getMethod (method) {
  const provider = this.client.getProviderForMethod(method, this)
  return provider[method].bind(provider)
}
```

2018-07-30 19:57 UTC, matthewjablack commented on examples/node/ethereum/multiple-providers.js
> +ethereum.addProvider(new X())
Change this to reflect chaining `addProvider`

2018-07-30 19:59 UTC, matthewjablack commented on examples/node/ethereum/multiple-providers.js
>    setClient (client) {
Remove all `setClient`

2018-07-30 20:00 UTC, matthewjablack commented on src/providers/bitcoin/BitcoinLedgerProvider.js
>      this._derivationPath = `44'/0'/0'/0`
@harshjv are we sure we want this to always be the default. Does this use legacy bitcoin address

2018-07-30 20:01 UTC, matthewjablack commented on src/providers/ethereum/EthereumLedgerProvider.js
>      this._derivationPath = `44'/60'/0'/0'/0`
@harshjv are we sure that this is the path we want for Ethereum everytime. Probably not as big of a deal since no segwit for Ethereum.

2018-07-31 10:33 UTC, harshjv commented on examples/node/ethereum/multiple-providers.js
> +const Provider = ChainAbstractionLayer.Provider
Or you can just do; (for consistency)

    const { Provider } = ChainAbstractionLayer

2018-07-31 10:33 UTC, harshjv commented on examples/node/ethereum/multiple-providers.js
> +    // const res = provider.signMessage(message, from)
You can remove the comments.

2018-07-31 10:35 UTC, harshjv approved these changes

2018-07-31 10:35 UTC, harshjv commented
@i3wgnit LGTM (just need to remove comments)

2018-07-31 14:15 UTC, i3wgnit commented on examples/node/ethereum/multiple-providers.js
> +const Provider = ChainAbstractionLayer.Provider
CAL is used below.

2018-07-31 16:34 UTC, merged