Bitcoin ledger send transaction
liquality/chainabstractionlayer pull request #22
Opened 2018-07-31 11:14 UTC by monokh

very much a WIP at the moment. Trying to get it working first before thinking about how to structure it.
Still if any suggestions please add 🙂

2018-08-01 13:07 UTC, harshjv requested changes

2018-08-01 13:07 UTC, harshjv commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +    return (await axios.get(`https://testnet.blockchain.info/balance?active=${address}&cors=true`)).data[address]
`BitcoinLedgerProvider` is just a signing provider. It should't have network specific calls in it.

2018-08-01 13:07 UTC, harshjv commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +        unspentInputs.push.apply(unspentInputs, utxos)
I am confused why did you need `.apply`.

2018-08-01 15:08 UTC, monokh commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +        unspentInputs.push.apply(unspentInputs, utxos)
`utxos` is an array. so this line is adding every element in `utxos` to `unspentInputs`

2018-08-01 15:13 UTC, monokh commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +    return (await axios.get(`https://testnet.blockchain.info/balance?active=${address}&cors=true`)).data[address]
How would you structure this?
We cannot have other provider methods for this because these are bitcoin specific functions that are not able to be implemented in any other chain. 
A utility module? 
Base provider module? I cannot imagine that one helping the situation

2018-08-02 06:11 UTC, harshjv requested changes

2018-08-02 06:11 UTC, harshjv commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +        unspentInputs.push.apply(unspentInputs, utxos)
you can just do;

```
unspentInputs.push(...utxos)
```

🤷🏻‍♂️

2018-08-02 09:44 UTC, monokh commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +        unspentInputs.push.apply(unspentInputs, utxos)
`[].push([])` is NOT the same as `[].push.apply([])`
Try this in node console to see the difference
```
let myarray = [1, 2, 3]
myarray.push([4, 5])
console.log(myarray)
```
compare it to 
```
let myarray = [1, 2, 3]
myarray.push.apply(myarray, [4, 5])
console.log(myarray)
```

2018-08-02 09:48 UTC, harshjv commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +        unspentInputs.push.apply(unspentInputs, utxos)
I got the point but we are already using ES6. Just use spread operator

```
unspentInputs.push(...utxos)
```

2018-08-02 09:55 UTC, monokh commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +        unspentInputs.push.apply(unspentInputs, utxos)
Good idea 👍 will do
waiting for further comments to implement all in one go

2018-08-02 10:00 UTC, harshjv requested changes

2018-08-02 10:00 UTC, harshjv commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +    return (await axios.get(`https://testnet.blockchain.info/balance?active=${address}&cors=true`)).data[address]
In this case, this will be `BitcoinLedgerTestnetBlockchainProvider`!

You can move everything except signing methods to `BitcoinRPCProvider` or create a new provider `BitcoinBlockchainProvider`.

You will be still able to use all the methods.

2018-08-02 10:10 UTC, monokh commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +    return (await axios.get(`https://testnet.blockchain.info/balance?active=${address}&cors=true`)).data[address]
I'm not quite following,
None of the methods here are to do with RPC, if we had a BitcoinBlockchainProvider, which methods would you carry over and how would you communicate between the providers? Shouldn't the communication of providers be only on normalized methods? there aren't any here that are not bitcoin specific

2018-08-02 15:27 UTC, monokh commented
@harshjv i actually realised that even putting into another module will have a lot of thinking to do on how to structure it. So I went with the minimal changes so we can unblock everyone for now.

2018-08-03 12:38 UTC, merged