JsonRpcProvider base class
liquality/chainabstractionlayer pull request #23
Opened 2018-07-31 12:36 UTC by harshjv

Currently, `jsonrpc` specific stuff is implemented in both `BitcoinRPCProvider` and `EthereumRPCProvider`. Now that we are supporting multiple-providers, moving `jsonrpc` stuff to `JsonRpcProvider` and `BitcoinRPCProvider/EthereumRPCProvider` leverages `JsonRpcProvider` for `jsonrpc` calls and checks.

`JsonRpcProvider` extends `Provider` base class and exposes `rpc` method.

So this is how provider stack will look like:

    const ChainAbstractionLayer = require('chainabstractionlayer')
    const { EthereumLedgerProvider, EthereumRPCProvider } = ChainAbstractionLayer.providers.ethereum

    const ethereum = new ChainAbstractionLayer()
    ethereum.addProvider(new EthereumLedgerProvider()) // no-dependency provider[0]
    ethereum.addProvider(new EthereumRPCProvider('http://localhost:8545')) // provider[1] can use methods added by provider[0]
    ethereum.addProvider(new EthereumLedgerProvider()) // provider[2] can use methods added by provider[1]

2018-08-01 20:57 UTC, i3wgnit commented on src/providers/JsonRpcProvider.js
> +  rpc (method, ...params) {
Just me being curious here, whats the difference between `_someMethod` and `someMethod`. Why the underscore sometimes?

2018-08-01 20:58 UTC, i3wgnit submitted a review, later dismissed
I like the direction this is going :+1:

2018-08-01 21:03 UTC, i3wgnit requested changes
I like the direction :+1:

2018-08-01 21:03 UTC, i3wgnit commented on src/providers/RpcError.js
> +    if (typeof msg === 'object' && msg !== null) {
Shouldn't this be `msg != null` ?

2018-08-01 21:03 UTC, i3wgnit commented on package.json
> +    "standard-error": "^1.1.0"
How big is this?

2018-08-02 06:14 UTC, harshjv commented on package.json
> +    "standard-error": "^1.1.0"
<img width="245" alt="screen shot 2018-08-02 at 11 43 53 am" src="https://user-images.githubusercontent.com/2311316/43565735-5efe4d68-9649-11e8-80c0-5e2d961f8aac.png">

2018-08-02 06:15 UTC, harshjv commented on src/providers/JsonRpcProvider.js
> +  rpc (method, ...params) {
Methods starting with `_` are private methods. (since in js there is no way of making a method private, using `_` as prefix, document generators mark them as `private` in docs.)

Since `rpc` method is explicitly exposed by the `JsonRpcProvider`, it has no `_`.

2018-08-02 06:20 UTC, harshjv commented on src/providers/RpcError.js
> +    if (typeof msg === 'object' && msg !== null) {
No. `null` is an `object`. checking with `!=` will also check for `undefined` which we don't want since first check is for `object`.

Umm, Instead, we can only do `msg != null`. Is that what you meant?

2018-08-02 10:02 UTC, monokh reviewed
Some small comments but no objection to merging in this state

2018-08-02 10:02 UTC, monokh commented on src/providers/JsonRpcProvider.js
> +      this._prepareRequest(method, params)
does this need it's own method? Would be easier to read with the content of the method just here since `_prepareRequest` isn't complicated. Unless it can be more complicated in the future

2018-08-02 10:02 UTC, monokh commented on src/providers/JsonRpcProvider.js
> +    if (username || password) {
should both username and password be required for this? Is there a case where an rpc node will have a username but no password or the opposite?

2018-08-02 13:43 UTC, i3wgnit commented on src/providers/RpcError.js
> +    if (typeof msg === 'object' && msg !== null) {
Oh, I didn't know that null was type object.

2018-08-02 13:51 UTC, i3wgnit commented on src/providers/RpcError.js
> +    if (typeof msg === 'object' && msg !== null) {
Why not make it extend props instead of replace then?

2018-08-02 14:14 UTC, i3wgnit approved these changes

2018-08-03 07:59 UTC, harshjv commented on src/providers/JsonRpcProvider.js
> +    if (username || password) {
Nope.

That's how http basic auth works. https://github.com/jshttp/basic-auth#with-vanilla-nodejs-http-server

2018-08-03 08:00 UTC, harshjv commented on src/providers/JsonRpcProvider.js
> +      this._prepareRequest(method, params)
It is this way for many reasons. First is, if you want to add prefix to request `id` or do some other modification, you just need to overwrite `_prepareRequest`.

2018-08-03 08:35 UTC, monokh commented on src/providers/JsonRpcProvider.js
> +    if (username || password) {
not sure if I explained properly, i know basic auth but does it make sense to provide only a password because in this case basic auth will be added. Anyway, this isn't anything very important

2018-08-03 08:36 UTC, monokh approved these changes

2018-08-03 08:36 UTC, monokh commented
Happy to merge when conflicts resolved

2018-08-03 08:37 UTC, merged