Fix circleci docker image
liquality/chainabstractionlayer pull request #27
Opened 2018-08-02 19:33 UTC by matthewjablack

This PR bumps `chainabstractionlayer-dev` docker version to 0.0.5 which includes `python2.7` which is required for `secp256k1` and `git-core` which is required for npm `usb` which is needed for `@ledgerhq/hw-transport-node-hid`. 

It also changes the usage of npm `usb` to use fork [https://github.com/mattBlackDesign/node-usb](https://github.com/mattBlackDesign/node-usb) which is a temporary fix. This fork removes functionality of usb, in order for it to work properly in circleci (Docker doesn't have access to host usb ).

2018-08-03 07:36 UTC, harshjv commented
Where is the latest source of this dockerfile? Can't find it here: https://github.com/ConsenSys/liquality_devops

2018-08-04 19:08 UTC, matthewjablack commented
`chainabstractionlayer-dev` Dockerfile associated with PR: [https://github.com/ConsenSys/liquality_devops/pull/5](https://github.com/ConsenSys/liquality_devops/pull/5)

2018-08-04 21:47 UTC, matthewjablack commented
For reference this PR solves two CircleCI issues

1. secp256k1 python requirement:

```
#!/bin/bash -eo pipefail
. /root/.nvm/nvm.sh && nvm use 8 && npm install
Now using node v8.11.3 (npm v5.6.0)

> secp256k1@3.5.0 install /root/chainabstractionlayer/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."


> secp256k1@3.5.0 rebuild /root/chainabstractionlayer/node_modules/secp256k1
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/root/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/root/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/root/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/root/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /root/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /root/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /root/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.4.0-130-generic
gyp ERR! command "/root/.nvm/versions/node/v8.11.3/bin/node" "/root/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
```

2. npm usb in docker 

```
#!/bin/bash -eo pipefail
. /root/.nvm/nvm.sh && nvm use 8 && npm test
Now using node v8.11.3 (npm v5.6.0)

> chainabstractionlayer@ test /root/chainabstractionlayer
> cross-env NODE_ENV=test mocha $npm_package_options_mocha

/root/chainabstractionlayer/node_modules/usb/usb.js:11
	throw new Error('Could not initialize libusb. Check that your system has a usb controller.');
	^

Error: Could not initialize libusb. Check that your system has a usb controller.
    at Object.<anonymous> (/root/chainabstractionlayer/node_modules/usb/usb.js:11:8)
    at Module._compile (module.js:652:30)
    at Module._compile (/root/chainabstractionlayer/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/root/chainabstractionlayer/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/chainabstractionlayer/node_modules/@ledgerhq/hw-transport-node-hid/src/listenDevices.js:4:1)
    at Module._compile (module.js:652:30)
    at Module._compile (/root/chainabstractionlayer/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/root/chainabstractionlayer/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/chainabstractionlayer/node_modules/@ledgerhq/hw-transport-node-hid/src/TransportNodeHid.js:11:1)
    at Module._compile (module.js:652:30)
    at Module._compile (/root/chainabstractionlayer/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/root/chainabstractionlayer/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/chainabstractionlayer/dist/index.cjs.js:1:2177)
    at r (/root/chainabstractionlayer/dist/index.cjs.js:1:124)
    at Module.<anonymous> (/root/chainabstractionlayer/dist/index.cjs.js:1:9490)
    at r (/root/chainabstractionlayer/dist/index.cjs.js:1:124)
    at /root/chainabstractionlayer/dist/index.cjs.js:1:923
    at Object.<anonymous> (/root/chainabstractionlayer/dist/index.cjs.js:1:16)
    at Module._compile (module.js:652:30)
    at Module._compile (/root/chainabstractionlayer/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/root/chainabstractionlayer/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/chainabstractionlayer/test/methods.js:10:31)
    at Module._compile (module.js:652:30)
    at Module._compile (/root/chainabstractionlayer/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/root/chainabstractionlayer/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /root/chainabstractionlayer/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/root/chainabstractionlayer/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/root/chainabstractionlayer/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/root/chainabstractionlayer/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! Test failed.  See above for more details.
Exited with code 1
```

2018-08-06 08:00 UTC, harshjv requested changes

2018-08-06 08:00 UTC, harshjv commented on package.json
> +    "usb": "https://github.com/mattBlackDesign/node-usb"
So you removed code that throws an error?

2018-08-06 08:01 UTC, harshjv requested changes

2018-08-06 08:01 UTC, harshjv commented on .circleci/config.yml
> +      - image: mblackmblack/chainabstractionlayer-dev:0.0.5
No need to change this. Once we merge https://github.com/ConsenSys/liquality_devops/pull/5, it will work automatically because it is an automated build.

2018-08-06 11:01 UTC, harshjv commented
The problem is with this file: https://github.com/LedgerHQ/ledgerjs/blob/master/packages/hw-transport-node-hid/src/listenDevices.js

Upstream error is tracked here: https://github.com/tessel/node-usb/issues/194

2018-08-06 11:45 UTC, harshjv commented
See #31 :)

2018-08-06 13:14 UTC, closed without merging