Convert getAddresses to return object and add coinType
liquality/chainabstractionlayer pull request #38
Opened 2018-08-08 05:45 UTC by matthewjablack

This PR adds global network config i.e. 

```
export default {
  bitcoin: {
    pubKeyHash: '00',
    scriptHash: '05',
    coinType: '0',
    explorerUrl: 'https://blockchain.info'
  },
  testnet: {
    pubKeyHash: '6F',
    scriptHash: 'C4',
    coinType: '1',
    explorerUrl: 'https://testnet.blockchain.info'
  },
  litecoin: {
    pubKeyHash: '30',
    scriptHash: '32',
    coinType: '2'
  },
  ethereum: {
    coinType: '60'
  },
  ethereum_classic: {
    coinType: '61'
  }
}

```

as well as segwit support for `getAddresses` with `coinType` specification (https://github.com/satoshilabs/slips/blob/master/slip-0044.md)

2018-08-08 10:41 UTC, harshjv requested changes

2018-08-08 10:41 UTC, harshjv commented on examples/browser/bitcoin/ledger.html
> +    const from = addresses[0].bitcoinAddress
Why is this changed? it should return an array of addresses. Not an object.

2018-08-08 10:41 UTC, harshjv commented on src/providers/ethereum/EthereumLedgerProvider.js
> +  constructor (chain = 'ethereum') {
Um, why?

Edit: saw EthereumUtil.js. Can we move network object to the root? Possibly, we can make symbol/const for the networks. i.e.

### network.js
```js
export default {
  BITCOIN: {
    TESTNET: {},
    MAINNET: {},
  },
  ETHEREUM: {
    RINKEBY: {},
    MAINNET: {},
  }, ...
}
```

and then,

```js
import { network } from 'chainabstractionlayer'
...
client.addProvider(new EthereumLedgerProvider({ network: network.ETHEREUM.MAINNET }))
```

We can enforce this signature for each provider, that it expects network in either an object or a value. What do you think? This way, we will be housing all network specific config in a single file.

2018-08-08 12:32 UTC, matthewjablack commented on examples/browser/bitcoin/ledger.html
> +    const from = addresses[0].bitcoinAddress
The majority of the time when you are getting addresses you are also looking to get the balance of that address as well. Made sense to include balance information, as well as utxo info for bitcoin chain.

2018-08-08 12:56 UTC, matthewjablack commented on src/providers/ethereum/EthereumLedgerProvider.js
> +  constructor (chain = 'ethereum') {
@harshjv I agree with your suggestion to move everything to one file. However I think each chain (including testnets) should be their own `chain` in this config. 

Looking at https://github.com/satoshilabs/slips/blob/master/slip-0044.md we can see that `Bitcoin Testnet` is a separate `coinType` than `Bitcoin` (similar with `Ethereum` and `Ethereum Classic`). However, `Rinkeby`, `Koven`, `Mainnet` all have the same `coinType`. So we can either specify `chainType` i.e. `Bitcoin` or `Ethereum` and then the underlying chain, or have that at root level. Thoughts?

2018-08-09 03:39 UTC, matthewjablack commented on examples/browser/bitcoin/ledger.html
> +    const from = addresses[0].bitcoinAddress
Updated to return array of addresses.

2018-08-09 06:07 UTC, matthewjablack commented
@harshjv PR updated with your suggestions

2018-08-10 12:26 UTC, harshjv approved these changes
LGTM

2018-08-11 01:48 UTC, i3wgnit approved these changes
:+1: long time overdue :) we now have access to all bitcoin forks

2018-08-11 09:19 UTC, harshjv requested changes

2018-08-11 09:19 UTC, harshjv commented on src/Client.js
> +  async getAddresses (segwit = false) {
`segwit` is a bitcoin specific term. is it okay to leave it in client.js?

2018-08-11 09:19 UTC, harshjv commented on src/Client.js
> +  async getAddresses (segwit = false) {
can we pass a `config` object instead? i.e. `{ segwit }`

```
async getAddresses (config = {})
```

and when fetching segwit addresses from bitcoin client, we can do;

```
client.getAddresses({ segwit: true })
```

Any thoughts?

2018-08-11 09:19 UTC, harshjv commented on src/networks.js
> +  testnet: {
Suppose this is accessed as `networks.testnet` somewhere in the codebase. How can a dev/user/auditor infer that this `networks.testnet` is Bitcoin testnet and not Ethereum testnet or any other coin's testnet? Because there's also a `networks.bitcoin`.

Any thoughts?

2018-08-13 12:48 UTC, matthewjablack commented on src/networks.js
> +  testnet: {
Perhaps we could specify the parent chain within the config

```
testnet: {
  parentChain: 'bitcoin'
}
```

Thoughts?

2018-08-13 13:43 UTC, harshjv approved these changes

2018-08-13 13:44 UTC, merged