Feat/solana integration
liquality/chainabstractionlayer pull request #432
Opened 2021-07-09 06:04 UTC by kraikov

### Description
Solana packages.

2021-07-14 09:11 UTC, monokh requested changes

2021-07-14 09:11 UTC, monokh commented on packages/solana-network/lib/index.ts
> +import { Network } from '@liquality/types'
Package name should be consistent with others i.e. `solana-networks` vs `solana-network`

2021-07-14 09:11 UTC, monokh commented on packages/solana-rpc-provider/lib/SolanaRpcProvider.ts
> +    return transactions.map((transaction) => normalizeTransaction(transaction))
I don't think this one needs to be normalized? I believe it's only used internally in the library and not exposed outside. I think it will make it more simpler in the code, instead of trying to access from`_raw` all the time

2021-07-14 09:11 UTC, monokh commented on packages/solana-rpc-provider/lib/SolanaRpcProvider.ts
> +export default class SolanaRpcProvider extends NodeProvider implements Partial<ChainProvider> {
should also be implementing `FeeProvider` ?

2021-07-14 09:11 UTC, monokh commented on packages/solana-swap-provider/lib/SolanaSwapProvider.ts
> +  signer: Keypair
These are unused>

2021-07-14 09:11 UTC, monokh commented on packages/solana-swap-provider/lib/SolanaSwapProvider.ts
> +    return sha256(message)
This will be unsafe, because it's deterministic and anyone can produce it. 
We use a standard message to generate the secret. So if you can just `sha256` the message for the secret, you can find the secret without the HTLC revealing it. In other chains we sign a message as that will produce a signature which only the generator of the secret can produce. 

Is there some way of doing the same with the solana keys?

2021-07-14 09:11 UTC, monokh commented on packages/solana-swap-provider/lib/SolanaSwapProvider.ts
> +    const { programId } = await this.getMethod('getConnectedNetwork')()
Rather explicitly pass the network into the provider constructor, this is how other swap providers are setup.

2021-07-14 09:11 UTC, monokh commented on packages/solana-utils/lib/index.ts
> +    transactionData.confirmations = 31
can you explain this magic number `31`?

2021-07-14 09:11 UTC, monokh commented on packages/solana-wallet-provider/lib/SolanaWalletProvider.ts
> +      address: account.publicKey.toString(),
if public key is available, can also add to the Address object. It's fine if it's the same as address

2021-07-14 09:11 UTC, monokh commented on test/integration/common.ts
> +      solana.addProvider(new SolanaSwapProvider())
you shouldn't need the swap providers to simply send some funds I imagine?

2021-07-14 09:11 UTC, monokh commented on packages/solana-utils/lib/index.ts
> +  _validateSecret(data.secret)
I think this should also validate secret and hash?
since we have the swap params available here, we can ensure that the secret matches the secret hash of the swap params. Using `validateSecretAndHash`

2021-07-14 09:11 UTC, monokh commented on packages/solana-swap-find-provider/lib/SolanaSwapFindProvider.ts
> +    const { programId } = await this.getMethod('getConnectedNetwork')()
better to explicitly pass the network

2021-07-14 14:39 UTC, AndonMitev commented on packages/solana-utils/lib/index.ts
> +    transactionData.confirmations = 31
So transactions have own statuses depending on the number of the confirmations, once when they reach state finalized it means there are 31 confirmations on the chain

2021-07-14 15:41 UTC, AndonMitev commented on test/integration/common.ts
> +      solana.addProvider(new SolanaSwapProvider())
nah i just follow the rest of the packages implemented in that scope

2021-07-19 12:48 UTC, AndonMitev commented on packages/solana-rpc-provider/lib/SolanaRpcProvider.ts
> +    return transactions.map((transaction) => normalizeTransaction(transaction))
It does, this is the single point where transactions are fetched and parsed, this is used in swap provider, swap find provider etc so this point is very important

2021-07-26 10:34 UTC, monokh commented on packages/solana-utils/lib/index.ts
> +    transactionData.confirmations = 31
ok, then can we use a combination of a constant and some comment to make sure it can be understable when reading the code?

2021-07-26 10:35 UTC, monokh approved these changes

2021-07-26 10:53 UTC, merged