Convert value to hex
liquality/chainabstractionlayer pull request #45
Opened 2018-08-12 14:48 UTC by harshjv

- [x] Fixes `sendTransaction` in EthereumMetaMaskProvider

2018-08-12 17:43 UTC, monokh requested changes

2018-08-12 17:43 UTC, monokh commented on src/providers/ethereum/EthereumMetaMaskProvider.js
> +    value = Number(value).toString(16)
I think as a standard, we should be using `BigNumber` anywhere we represent values, there may be some unexpected results when numbers go over the [MAX_SAFE_INT](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)

2018-08-13 07:33 UTC, harshjv commented on src/providers/ethereum/EthereumMetaMaskProvider.js
> +    value = Number(value).toString(16)
This hotfix is only for `sendTransaction` which is blocking https://github.com/ConsenSys/liquality-atomic-swap/pull/7.

For numbers, I do agree to go with a library like BigInt (cool because native support is coming) or BigNumber.js. We will explore more edge cases when we dive into testing :)

2018-08-13 09:31 UTC, monokh commented on src/providers/ethereum/EthereumMetaMaskProvider.js
> +    value = Number(value).toString(16)
Going over MAX_SAFE_INT itself could mean the value would be broken so since we are here i thought we might as well make the right decisions. BigNumber if i remember right is already included in CAL, so only need to replace `Number` with `BigNumber`

2018-08-13 09:33 UTC, monokh commented on src/providers/ethereum/EthereumMetaMaskProvider.js
> +    value = Number(value).toString(16)
also i don't think this blocks https://github.com/ConsenSys/liquality-atomic-swap/pull/7 per se.  that PR can just assume that this will be fixed

2018-08-13 12:48 UTC, monokh approved these changes
LGTM

2018-08-13 12:49 UTC, merged