feat: export private key from js wallets
liquality/chainabstractionlayer pull request #462
Opened 2021-10-11 23:37 UTC by b0b4456

https://linear.app/liquality/issue/LIQ-329/implement-getprivatekey-functionality-in-chainabstractionlayer

2021-10-12 08:12 UTC, harshjv requested changes

2021-10-12 08:12 UTC, harshjv commented on packages/bitcoin-js-wallet-provider/lib/BitcoinJsWalletProvider.ts
> +    return pair.privateKey?.toString('hex')
do we need `?` (can `pair.privateKey` be empty?)

2021-10-12 08:12 UTC, harshjv commented on test/integration/wallet/bitcoinWallet.test.ts
> +      expect(key).not.to.be.empty
can you update your tests to verify actual priv key instead of `not.to.be.empty`?

2021-10-12 13:35 UTC, b0b4456 commented on packages/bitcoin-js-wallet-provider/lib/BitcoinJsWalletProvider.ts
> +    return pair.privateKey?.toString('hex')
according to typescript it can be empty

2021-10-12 13:37 UTC, b0b4456 commented on test/integration/wallet/bitcoinWallet.test.ts
> +      expect(key).not.to.be.empty
for eth and near yes, I was able to print out a string in the console and could paste that in. But for btc i can't actually run the tests, is it because I'd need bitcoind running locally ?

2021-10-13 12:27 UTC, harshjv approved these changes
LGTM

2021-10-13 14:24 UTC, merged