fix: improving terra usdt swaps
liquality/chainabstractionlayer pull request #483
Opened 2021-12-03 15:24 UTC by skeremidchiev

### Description
(LIQ-648)[https://linear.app/liquality/issue/LIQ-648/small-network-fee-displayed-on-the-swap-page-but-in-actual-the-fee]

Describe the purpose of this PR

### Submission Checklist :pencil:

2021-12-03 16:11 UTC, bradleySuira approved these changes
LGTM

2021-12-07 18:56 UTC, harshjv requested changes

2021-12-07 18:56 UTC, harshjv commented on packages/terra-wallet-provider/lib/TerraWalletProvider.ts
> +        taxFee = new BigNumber((await this.getTaxFees(value.toNumber() / 1_000_000, this._feeAsset, false)) * 1_000_000)
can we please split this statement into multiple lines with variable names? it will make the code more readable.

2022-02-02 12:06 UTC, monokh approved these changes

2022-02-03 07:14 UTC, merged