Implement getBalance for Bitcoin
liquality/chainabstractionlayer pull request #49
Opened 2018-08-23 06:43 UTC by i3wgnit

### Description

Implement getBalance for BitcoinLedgerProvider
First merge #48 before this one.

### Parts

- [x] Implement `getBalance` method
- [x] Make an interface for the previous bullet point in the `Client`

2018-08-23 09:29 UTC, monokh commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +  async getBalance (config = { segwit: false }) {
i find it quite un normalized that the functions accept a config like that... the same interface won't exist for ethereum. The correct way i believe should be to set this flag on the provider constructor, but that's a different issue that doesn't need to be addressed here.

2018-08-23 09:32 UTC, monokh commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +    return usedAddresses.reduce((acc, detail) => acc + detail.value, 0)
This type of thing is a good candidate for a unit test. Mock _connectToLedger and _getSpendingDetails and see if the function does what you expect. Again different issue 🙂 feel free to address it whenever in your priorities

2018-08-23 09:32 UTC, monokh approved these changes
LGTM, minor comments but nothing that can't be done separately

2018-08-30 09:06 UTC, monokh requested changes
looks fine but again can you include an example so we can see how to use this? similarly for the ethereum version

2018-08-31 00:56 UTC, merged

2018-08-31 04:30 UTC, matthewjablack commented on src/Client.js
> +      if (!addresses.every(addr => (/^[A-Fa-f0-9]+$/.test(addr)))) {
Doesn't this need to be removed since bitcoin addresses are not hex strings?