feat: Integrate moralis as nft provider
liquality/chainabstractionlayer pull request #548
Opened 2022-06-06 10:09 UTC by AndonMitev

2022-06-06 12:11 UTC, kraikov requested changes

2022-06-06 12:11 UTC, kraikov commented on packages/evm/lib/nft/MoralisNftProvider.ts
> +import { EvmNftProvider } from 'lib/nft/EvmNftProvider';
fix this path

2022-06-06 12:11 UTC, kraikov commented on packages/evm/lib/nft/OpenSeaNftProvider.ts
> +import { NFTAsset, NftTypes } from 'lib/types';
path

2022-06-09 10:45 UTC, monokh commented on packages/evm/lib/nft/OpenSeaNftProvider.ts
> +        const data = nfts.assets.map((nft: any) => {
no :any, type the response from opensea

2022-06-09 10:59 UTC, monokh requested changes

2022-06-09 10:59 UTC, monokh commented on packages/evm/lib/nft/OpenSeaNftProvider.ts
> +        const data = nfts.assets.map((nft: any) => {
no :any, type the response from opensea

2022-06-09 10:59 UTC, monokh commented on packages/evm/lib/nft/MoralisNftProvider.ts
> +        Moralis.start(moralisConfig).then();
what is going on here? if `.start()` needs to be awaited, you can't do it like this. You can call `start` on demand when `fetch` is called for example. And after it's started, not call it again

2022-06-09 10:59 UTC, monokh commented on packages/evm/lib/nft/MoralisNftProvider.ts
> +            } as NFTAsset;
`as NFTAsset` is usually a sign that the typing here is not correct and you are force ignoring some type errors. What happens if you remove it ?

2022-06-09 10:59 UTC, monokh commented on packages/evm/lib/nft/CovalentNftProvider.ts
> +                        return resp as NFTAsset;
shouldn't need `as` if you define the response type of the api

2022-06-09 10:59 UTC, monokh commented on packages/evm/lib/nft/EvmNftProvider.ts
>      constructor(walletProvider: EvmBaseWalletProvider<BaseProvider>, httpConfig: ClientTypes.AxiosRequestConfig) {
replace `httpConfig` with the parameters that client needs to pass. e.g. `url`, `apiKey`

2022-06-09 10:59 UTC, monokh commented on packages/evm/lib/nft/CovalentNftProvider.ts
> +            .filter(Boolean);
I think you are looking for `reduce` 😄  Inside reduce you can check if nft, and if so convert and add to the accumulator

2022-06-09 10:59 UTC, monokh commented on packages/evm/package.json
> +        "moralis": "^1.8.0"
pin the version

2022-06-09 10:59 UTC, monokh commented on packages/evm/lib/nft/MoralisNftProvider.ts
> +            } as NFTAsset;
same as below

2022-06-09 14:37 UTC, kraikov commented
Usage:

```ts
import * as EVM from "@chainify/evm";

const infuraApi = "";
const mnemonic = "";

const chainProvider = new EVM.EvmChainProvider(
  {
    ...EVM.EvmNetworks.rinkeby,
    rpcUrl: `https://rinkeby.infura.io/v3/${infuraApi}`,
  },
  null,
  null,
  false
);

const walletProvider = new EVM.EvmWalletProvider({ mnemonic }, chainProvider);

// Fetch NFTs from OpenSea
const openSea = new EVM.OpenSeaNftProvider(walletProvider, {
  url: "https://rinkeby-api.opensea.io/api/v1/",
  apiKey: undefined, // define for mainnet
});
openSea.fetch().then(openSea.fetch().then(console.log()));

// Fetch NFTs from Moralis
const moralis = new EVM.MoralisNftProvider(walletProvider, {
  url: "",
  apiKey: "",
  appId: "",
});
moralis.fetch().then(console.log);

// Fetch NFTs from Covalent (does not work with Rinkeby)
const covalent = new EVM.CovalentNftProvider(walletProvider, {
  url: "https://api.covalenthq.com/v1",
  apiKey: "",
});
covalent.fetch().then(console.log);

// Transfer
moralis
  .transfer(
    "0xe10cd16070101ffe6b5bdd380c3c7f0e8fcec84d", // nft contract address
    "0x8072aC361d0ee237EFE0883198613d8d121Ee98d", // recipient
    ["1"], // token ids
    ["1"] // token amounts only applicable for ERC1155
  )
  .then(console.log);

```

2022-06-09 14:38 UTC, kraikov commented
Responses:

OpenSea:

```js
[
  {
    asset_contract: {
      address: '0xe10cd16070101ffe6b5bdd380c3c7f0e8fcec84d',
      external_link: null,
      image_url: null,
      name: 'test1',
      symbol: 'test1'
    },
    collection: { name: 'test1 - uRJXEljW05' },
    description: 'Bitcoin, often described as a cryptocurrency, a virtual currency or a digital currency - is a type of money that is completely virtual.',
    external_link: null,
    id: 57292149,
    image_original_url: 'ipfs://QmWsDVqrE5wp2ct6CxXzRaZeG8QxuJR7ALiuLaKrJ1UvYf/0000000000000000000000000000000000000000000000000000000000000001.png',
    image_preview_url: 'https://lh3.googleusercontent.com/rfjtgTE04GAX2WhKqDTFx1ZHd-uJEdhqD9XCyIDurHTr5KoBthbAl1s_LUJ1-2XSVZRoObd40J68mNuq8QpX7ZNBdoWfdr-JCA7fU5c=s250',
    image_thumbnail_url: 'https://lh3.googleusercontent.com/rfjtgTE04GAX2WhKqDTFx1ZHd-uJEdhqD9XCyIDurHTr5KoBthbAl1s_LUJ1-2XSVZRoObd40J68mNuq8QpX7ZNBdoWfdr-JCA7fU5c=s128',
    name: 'test1',
    token_id: '1'
  }
]
```

Moralis:
```js
[
  {
    asset_contract: {
      address: '0xe10cd16070101ffe6b5bdd380c3c7f0e8fcec84d',
      name: 'test1',
      symbol: 'test1'
    },
    collection: { name: 'test1' },
    token_id: '1',
    name: 'Bitcoin 1',
    description: 'Bitcoin, often described as a cryptocurrency, a virtual currency or a digital currency - is a type of money that is completely virtual.',
    image_original_url: 'ipfs://QmWsDVqrE5wp2ct6CxXzRaZeG8QxuJR7ALiuLaKrJ1UvYf/0000000000000000000000000000000000000000000000000000000000000001.png',
    image_preview_url: 'ipfs://QmWsDVqrE5wp2ct6CxXzRaZeG8QxuJR7ALiuLaKrJ1UvYf/0000000000000000000000000000000000000000000000000000000000000001.png',
    image_thumbnail_url: 'ipfs://QmWsDVqrE5wp2ct6CxXzRaZeG8QxuJR7ALiuLaKrJ1UvYf/0000000000000000000000000000000000000000000000000000000000000001.png',
    external_link: undefined
  }
]
```


Covalent
``` js
[
  {
    token_id: '36500',
    asset_contract: {
      address: '0xaaf03a65cbd8f01b512cd8d530a675b3963de255',
      name: 'Seekers',
      symbol: 'SEEKERS'
    },
    collection: { name: 'Seekers' },
    name: null,
    description: null,
    external_link: 'https://seekers.xyz',
    image_original_url: 'https://nft.seekers.xyz/seekers/seeker_36500.png',
    image_preview_url: 'https://nft.seekers.xyz/seekers/seeker_36500.png',
    image_thumbnail_url: 'https://nft.seekers.xyz/seekers/seeker_36500.png'
  }
]
```

2022-06-09 15:00 UTC, monokh approved these changes

2022-06-09 15:04 UTC, merged