Swap creation fix
liquality/chainabstractionlayer pull request #56
Opened 2018-09-03 13:45 UTC by monokh

### Description

Small fixes to make the initiation of swap work

### Parts

- [x] Removed hex validation for generate swap - only ethereum addresses are in hex
- [x] Fixed example

2018-09-03 14:52 UTC, harshjv requested changes
Just a small modification required! Other than that, LGTM

2018-09-03 14:52 UTC, harshjv commented on examples/browser/bitcoin/ledger-send-transaction.html
> +        bitcoin.sendTransaction(null, parseInt($('#scriptValue').val()), $('#toScript').val()).then(result => {
this will fail for floats. e.g. 0.1 ETH

2018-09-03 14:52 UTC, harshjv commented on src/Client.js
> -    if (!(/^[A-Fa-f0-9]+$/.test(recipientAddress))) {
nice catch!

2018-09-03 14:52 UTC, harshjv commented on src/providers/bitcoin/BitcoinLedgerProvider.js
> +    if (data) {
Nice catch, again!

2018-09-03 14:52 UTC, harshjv commented on src/providers/bitcoin/BitcoinUtil.js
> +  const addr = pubKeyHashToAddress(pubKeyHash, network, type)
Another one! Thanks Mo!

2018-09-03 14:52 UTC, harshjv commented on examples/browser/bitcoin/ledger-send-transaction.html
> +        bitcoin.sendTransaction(null, parseInt($('#scriptValue').val()), $('#toScript').val()).then(result => {
you can change it to `parseFloat` or use `Number`

2018-09-03 15:42 UTC, monokh commented on examples/browser/bitcoin/ledger-send-transaction.html
> +        bitcoin.sendTransaction(null, parseInt($('#scriptValue').val()), $('#toScript').val()).then(result => {
I believe the interface for `sendTransaction` accepts the smallest denomination of the amount. so 1 here would be 1 satoshi or wei. So I think we shouldn't be parsing as floats for the example unless we were doing some conversion from the various denominations

2018-09-06 08:19 UTC, monokh commented
comments have been addressed and don't see anything really contentious here so merging

2018-09-06 08:19 UTC, merged